### ISSUE TITLE
When storage account is "privatized," should Disable public network access

### ISSUE THREAD

**Issue by SvenAelterman** [dcampman/Azure-SRE#1]
I think this is relatively new: 
![image](https://user-images.githubusercontent.com/17446043/166166953-318d0d82-abae-4a66-9279-b425e9f83e30.png)

**Comment by SvenAelterman** [comment]
This might have consequences for the trusted Azure services, so we'll need to investigate the impact.

**Comment by dcampman** [comment]
Found the correct property to disable the firewall completely. 'publicNetworkAccess' should be set to 'Disabled' when we want the firewall disabled. I updated the storage account module and re-ran the template on a new deployment. It doesn't seem to have an effect on the deployed resources such as event grid topics, however ill be testing this more.

**Comment by dcampman** [comment]
tested and found no change to azure services access to storage account. Event topics are still generated and data factory pipeline still works fine. Considering this resolved for now. As this feature is improved, there may be more effort required.
