### ISSUE TITLE
Name of ADF pipeline is hardcoded in many places

### ISSUE THREAD

**Issue by SvenAelterman** [dcampman/Azure-SRE#4]
`pipe-data_move` is hardcoded in different files.

Suggestion:

- Define the pipeline name as an optional parameter in adf.bicep
    `param pipelineName string = 'pipe-data_move'`
- Output the pipeline name from adf.bicep
    `output pipelineName string = pipelineName`
- Reference the output in the rest of data.bicep
    `ingestPipelineName: adf.outputs.pipelineName`

**Comment by SvenAelterman** [comment]
It's also hardcoded in logicAppWorkflow.json

**Comment by dcampman** [comment]
made the change, will test tonight when other changes are in.

**Comment by dcampman** [comment]
resolved
